language: node_js
node_js:
    - "0.10"

before_install:
    - npm install -g grunt-cli

before_script:
    - bower install --force-latest 

cache:
    - node_modules
    - app/scripts/bower_components
