language: python

python:
    - "3.3"
    - "3.4"

node_js:
    - "0.10"

services:
    - mongodb
    - elasticsearch
    - redis-server

before_install:
    - npm install -g grunt-cli bower

install:
    - cd server && pip install -r requirements.txt --use-mirrors && cd ..
    - cd client && npm install && cd ..
    - cd client && bower install --force-latest && cd ..

script:
    - cd server && nosetests && cd ..
    - cd server && behave --format progress2 --logging-level ERROR && cd ..
    - cd server && LDAP_SERVER="ldap://sourcefabric.org" LDAP_BASE_FILTER="OU=Superdesk Users,dc=sourcefabric,dc=org" behave --format progress2 --logging-level ERROR && cd ..
    - cd server && flake8 && cd ..
    - cd client && npm test && cd ..

after_success:
    - cd client && grunt coveralls && cd ..

sudo: false
