language: python

env:
    - TARGET=client
    - TARGET=server

python:
    - "3.3"
    - "3.4"

node_js:
    - "0.10"

services:
    - mongodb
    - elasticsearch
    - redis-server

before_install:
    - if [ "${TARGET}" = "client" ]; then
        npm install -g grunt-cli bower
        ;
      fi

install:
    - if [ "${TARGET}" = "server" ]; then
        cd server && pip install -r requirements.txt --use-mirrors && cd ..
        ;
      fi
    - if [ "${TARGET}" = "client" ]; then
        cd client &&
        npm install &&
        bower install --force-latest &&
        cd ..
        ;
      fi

script:
    - if [ "${TARGET}" = "server" ]; then
        cd server &&
        nosetests &&
        behave --format progress2 --logging-level ERROR &&
        LDAP_SERVER="ldap://sourcefabric.org" LDAP_BASE_FILTER="OU=Superdesk Users,dc=sourcefabric,dc=org" behave --format progress2 --logging-level ERROR &&
        flake8 &&
        cd ..
        ;
      fi
    - if [ "${TARGET}" = "client" ]; then
        cd client && npm test && cd ..
        ;
      fi

after_success:
    - if [ "${TARGET}" = "client" ]; then
        cd client && grunt coveralls && cd ..
        ;
      fi

sudo: false
