language: python
python:
    - "2.7"
    - "3.3"

services:
    - mongodb
    - elasticsearch

install: "pip install -r requirements.txt --use-mirrors"

script:
    - nosetests
    - behave
    - flake8 superdesk features *.py
