language: python
python:
    - "3.3"
    - "3.4"

services:
    - mongodb
    - elasticsearch

install: "pip install -r requirements.txt --use-mirrors"

script:
    - nosetests
    - behave
    - flake8
